language: node_js
node_js:
- 8.4.0
sudo: required
cache:
  directories:
  - node_modules
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm start
- npm run ng-deploy
- ls -l
script:
- docker build -t $DOCKER_USERNAME/se234-lab10-client .
- docker push $DOCKER_USERNAME/se234-lab10-client
service: docker
env:
  global:
  - secure: bxVne/imtmJQmYinXuMnHcKi9I7yPCuDpduEb6aby5tv2h462XCbprJvwZsjqdtfFd35XBs2kRSSgjj4H6BiMsS1oXmdSdqFjm4EUm67Ny0dReMIi7kMY2NVx3pHMPv7Mg/IpeTjD0tIPSjPVgEaNmbZMLyv4jIcVw2xAnn7CSclxcEpCH9Rq4s//iK1589/Wwf6I5Ytuc2frpkJ9GPqY9JNEiaHCQ4LYpOeH+gxqm18oApqjCEhdfxKekOlmplX/GqabDPssPWZ+hRXNbLMgwB+TRv5N2R9jXspHwWvn78N1nhuzM7tTlFv8dcxanWAnI1kie0hnVi05heyOtGU1rl1eiA5ERN9W6l5WiHIQgvBdbQr37HNg4aE86xupPw/Rn9KCuKqKbJIeg0Essdnp8GD3Xq1A6SXDsVVAZIIQ1HBrV8NV/H0YNJpBkdyPjv0ggj8qQ1jhz2IJAzG4ZlzpnV9SNII7Q/1sq+iOfAySgUpFBXoS1FVyJsSGCNGkc29h5wFCritSiczyJfGiHJP8GsqPElFvAdKU9gwlA6UjrL99Ip+CM8F1tlYkROhxqdRtj2Qn30yTAwLMxGgUeB4oVpXnlGsNNrSB14vfq+l3uRgR/4OPAUqSjNJm+1J0jIWuzYDwonz/ThMX3dTduDjFVp+IbTMvgpZD0S/Mk9QxRA=
  - secure: D6uou1eX7mlvFrCdEoDU7sk2tnhGSqAChYS/bZpYS7AYXqYtfsvXWn0VFIjI04To1R4e661NHFXTYBP8+cIXQzWKVs7jCsScikuEbmr4hS1kREAP8ZM9Y+2jrcFmfNMvICPypSsAynHkTMY/3Nlgvnsgi3bjvI3ABb9tdqNba5trDGKVTIHowdPmSc8mf9ibW+eH0+Qcr8uV2GvCxvyLldzlhNNoQjePA/TxxSEK2sV8LxIJCr3heIzn/3clU9B4trzB860e4gjsjYDlOVM3JVy/Ga7qlTZ39qk0jHmNKoKpZBKvE/x3fkXAJNp0xJHP5LpxPht66tNOMY+mbng498U3YO/0WLcoCSieLseMled9hsRM3mE7p5/qPAEKBqSwp066rj1VPfz2zp30fnsKiDgVMyxXv5639q7/6/pKMIVnTnlA8dsR3NbD5+MNgHSGLCuKSwNidZ2j444hhjmWL8Y4TfaGabGSQpHygpO7QuYWGfH1GyRclf5HjiRK1q+LtQu7uyLXmpimsuCKO1oPMED4rTebXKX1WvQ7Qs6T4EmOIiy3vl9Iropr7UvN5xDCOis5eyKZsPYYuBxQkIiEHggMpjNCnVx9AbNRestoSLEdHLD2KGSdeeFnHxach5hdWFA5aEd7DgOIfutdc26vHjM5XmPTsBAXPG6fuGyIZ2k=
